Turn CAPMC power on/off/reinit into a shim that calls PCS
Cray-HPE/hms-capmc pull request #78
Opened 2023-01-03 21:18 UTC by mjendrysik-hpe

### Summary and Scope

Convert the CAPMC xname_[on/off/reinit] APIs into shims that call PCS.

### Issues and Related PRs

LIST AND CHARACTERIZE RELATIONSHIP TO JIRA ISSUES AND OTHER PULL REQUESTS. BE SURE LIST DEPENDENCIES.

* Resolves CASM-XYZ
* Change will also be needed in `<insert branch name here>`
* Future work required by CASM-ABC
* Merge with `<insert PR URL here>`
* Merge before `<insert PR URL here>`
* Merge after `<insert PR URL here>`

### Testing

LIST THE ENVIRONMENTS IN WHICH THESE CHANGES WERE TESTED.

Tested on:

* `<drink system>`
* Craystack
* CMS base-box
* Virtual Shasta

Were the install/upgrade based validation checks/tests run?(goss tests/install-validation doc)
Were continuous integration tests run? Y/N   If not, Why?
Was an Upgrade tested?                 Y/N   If not, Why?
Was a Downgrade tested?                Y/N   If not, Why?
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?

WHAT WAS THE EXTENT OF TESTING PERFORMED? MANUAL VERSUS AUTOMATED TESTS (UNIT/SMOKE/OTHER)
HOW WERE CHANGES VERIFIED TO BE SUCCESSFUL?

### Risks and Mitigations

HAS A SECURITY AUDIT BEEN RUN? (./runSnyk.sh)
ARE THERE KNOWN ISSUES WITH THESE CHANGES?
ANY OTHER SPECIAL CONSIDERATIONS?

INCLUDE THE FOLLOWING ITEMS THAT APPLY. LIST ADDITIONAL ITEMS AND PROVIDE MORE DETAILED INFORMATION AS APPROPRIATE.

Requires:

* Additional testing on bare-metal
* Compute nodes
* 3rd party software
* Broader integration testing
* Fresh install
* Platform upgrade

2023-01-03 21:24 UTC, nieuwsma commented
need to bump version numbers 😄

2023-01-03 21:41 UTC, mjendrysik-hpe commented
> need to bump version numbers 😄

Yeah yeah yeah. If you notice the PR is in Draft mode.

I had no idea what new checks I was going to run into.

2023-01-09 22:31 UTC, schooler-hpe commented on CHANGELOG.md
> +## [3.0.0] - 2022-01-03
The year/date could use an update here.

2023-01-09 22:32 UTC, schooler-hpe commented on CHANGELOG.md
> +- Converted xname_[on/off/reinit] to use PCS for power operations
get_xname_status as well.

2023-01-09 22:36 UTC, schooler-hpe approved these changes

2023-01-10 15:18 UTC, nieuwsma requested changes

2023-01-10 15:18 UTC, nieuwsma commented on docker-compose.test.ct.yaml
> +      - PCS_URL=http://cray-power-control:28007/testing
what is this URL? /testing??

2023-01-10 19:01 UTC, nieuwsma approved these changes

2023-01-10 19:03 UTC, alvarez3-hpe approved these changes

2023-01-10 19:09 UTC, merged